# Logistic Regression
Predicting a class (Category) from independent variables

## Libraries

In [1]:
# Standard
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Library - SKLEARN

In [2]:
# Load Logistic Regression Libraries - SKLEARN
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

## Data

In [3]:
# Create a sample numpy data
x = np.arange(10). reshape(-1,1) #single column data, IV
y = np.array([0,0,0,0,1,1,1,1,1,1])  # DV
print(x, '\n', y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 
 [0 0 0 0 1 1 1 1 1 1]


## Create Model

In [4]:
logModel = LogisticRegression(solver = 'liblinear', random_state=0)
logModel.fit(x, y)
# or logModel = LogisticRegression(solver = 'liblinear', random_state=0).fit(x, y)

LogisticRegression(random_state=0, solver='liblinear')

## Model Statistics

In [5]:
logModel.classes_   # different classes of DV

array([0, 1])

In [6]:
logModel.intercept_  # intercept in  y = intercept + coeff * x

array([-1.04608067])

In [7]:
logModel.coef_   #coeff also called odds ratio
# if x changes by one unit, probability of y changes by .51

array([[0.51491375]])

In [ ]:
# y = -1.04 + .51 * x

## Model Evaluate

In [8]:
logModel.predict_proba(x)  # 2 column output : prob of 0 (left) and 1 (right)
# if first row values are .74, and .25
#here when x = 0, acutal predicted class is 0; 
#while predicted class is 0  with probability of 0.74 and 
#predicted class is 1 with probability with 0.25

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [9]:
logModel.predict(x) # Predicted classes instead of probabilities
# here if first value is 0, then for x= 0, predicted class is 0 which is same as original class

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

## Model Accuracy

In [ ]:
logModel.score(x, y)  
# if value is .9, 9 times out of 10, predicted class is correct (same as orginal)

### Confusion Matrix

In [ ]:
confusion_matrix(y, logModel.predict(x))
# TN, FP  = 3, 1
# FN, TP  = 0, 6
# we should have max values in True Negative(TN) and True Positive(TP)

In [ ]:
# Draw Heat Map to visually see the outut
cm = confusion_matrix(y, logModel.predict(x))
sns.heatmap(cm, annot=True)

### Classification Report

In [ ]:
classification_report(y, logModel.predict(x))

In [ ]:
# output values
# Accuracy - .91

## End Here